### PR TITLE
Added get pixel size process.

### PR DESCRIPTION
**Pull request by mikoto2000**
I try add get pixel size process.(See: #44)

- Change recv length to 16 (short x 4(row, col, xpixel, ypixel))
- Delete the parts that have been overwritten with zeros

Please check it.

image
(rows, cols, xpixel, ypixel)

termsize.py: https://github.com/mikoto2000/sixelPreviewer/blob/master/termsize.py

### CODE REVIEW

**Comment by mintty** [comment]
`struct winsize` is 8 bytes long, it is wrong to read 16 bytes from the socket. That's why the backend blocks until you feed in 8 more bytes by hitting keys.
After fixing this, the pixel size is properly conveyed and properly reported in various distributions. However, a number of distributions do not support the pixel values anyway.

Please fix the patch and re-release as 0.14. The current release can be deleted.
```
diff --git a/src/wslbridge2-backend.cpp b/src/wslbridge2-backend.cpp
old mode 100755
new mode 100644
index e3b3ad2..cd81e4a
--- a/src/wslbridge2-backend.cpp
+++ b/src/wslbridge2-backend.cpp
@@ -256,9 +256,9 @@ int main(int argc, char *argv[])
                             s++;
                             len--;
                             // ensure 8 more bytes are loaded for winsize
-                            while (readRet > 0 && len < 16)
+                            while (readRet > 0 && len < 8)
                             {
-                                readRet = recv(ioSockets.inputSock, s + len, 16 - len, 0);
+                                readRet = recv(ioSockets.inputSock, s + len, 8 - len, 0);
                                 if (readRet > 0)
                                 {
                                     len += readRet;

**Comment by mikoto2000** [comment]
@mintty
Thank you for pointing that out, you were right.
The problem of having to press Enter several times has been fixed in my environment.

I will fix this patch and create a Pull Request.

**Comment by Biswa96** [comment]
I have added the fix in v0.13 release.

**Comment by mintty** [comment]
Thank you, my test packages work fine. Can we have it as a release please?

**Comment by Biswa96** [comment]
v0.13 has the fix, I have re-tagged it (not professional, I know).

**Comment by mintty** [comment]
Ah, thanks, that's OK.

**Pull request merged**
