### PR TITLE
Added -D option for specifying directory in WSL path format

### PR DESCRIPTION
**Pull request by dxhisboy**
Hi, I've added a -D option for specifying directory in WSL path format.
Also, you can give me a little code formatting guidelines if some formatting is needed.

### CODE REVIEW

**Comment by Biswa96** [comment]
Thank you 🎉

@mintty was asking about this option. He may provide some useful opinions. One thing I like to make the options (long and short) somewhat similar with GNU tools (tar, grep, bash).

**Comment by mintty** [comment]
From the point of view of launching from mintty (wsltty), the only directory I need to specify is the user's home directory. This was available with wslbridge(1) as `-C~`. I don't mind to change it to `-D~` but I hope the shorcut `~` is going to work.

**Comment by dxhisboy** [comment]
> Thank you 🎉
> 
> @mintty was asking about this option. He may provide some useful opinions. One thing I like to make the options (long and short) somewhat similar with GNU tools (tar, grep, bash).

Maybe I cannot come up with a proper option name other than "--directory" which is already used in specifying a windows path. Maybe I can help in modifying makefiles to achieve static linking.

**Comment by dxhisboy** [comment]
> From the point of view of launching from mintty (wsltty), the only directory I need to specify is the user's home directory. This was available with wslbridge(1) as `-C~`. I don't mind to change it to `-D~` but I hope the shorcut `~` is going to work.

Waiting for a tabbed version of mintty for so long. Currently I'm using fatty.

**Comment by mintty** [comment]
Is that a trading offer? Option vs. feature :)
You are aware of the tab discussion in mintty? And the fact that "virtual tabs" are available, with switching accessible via context menu, and including a framework for a tab bar? See mintty issue 699.

**Comment by Biswa96** [comment]
I was thinking about not using short options at all. Long options will be like `windir` or `wsldir` etc. It will remove any confusion. What is your opinion?

This PR is OK now.

**Comment by dxhisboy** [comment]
> I was thinking about not using short options at all. Long options will be like `windir` or `wsldir` etc. It will remove any confusion. What is your opinion?

I think this is a awesome idea. But leaving `--directory` for backward compatibility?

**Comment by mintty** [comment]
Short option names are useful for the use case of invoking a tool manually.
For integration in wsltty, it does not matter and I do not care. My only concern is the option *value* `~`.

**Comment by dxhisboy** [comment]
> Is that a trading offer? Option vs. feature :)
> You are aware of the tab discussion in mintty? And the fact that "virtual tabs" are available, with switching accessible via context menu, and including a framework for a tab bar? See mintty issue 699.

I found this functionality, while I'm usually a KDE user...

> Short option names are useful for the use case of invoking a tool manually.
> For integration in wsltty, it does not matter and I do not care. My only concern is the option _value_ `~`.


In my tests, `~` can be passed into `-D` and works. Just like at https://github.com/dxhisboy/fatty-wslbridge
While, I think it should not work as `chdir` should not expand `~`...

**Comment by dxhisboy** [comment]
I did the modifications to use `--windir` and `--wsldir`

**Comment by Biswa96** [comment]
@dxhisboy I'm working on something in this repo. Please contact me or create an issue before making a pull request. Otherwise we could clash with same feature/modification. 

Thank you for your kind contribution 🎊

**Pull request merged**
